apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: api-deployment
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-deployment
    spec:
      containers:
      - image: local/oka-api
        name: api
        resources: {}

